#图片上传路径映射 自定义属性
upload:
  picture:
    path: "D:/springboot/upload/"

#数据库备份路径
sqlbackup:
  path: "D:/springboot/sql/"
  staticPath: "D:/springboot/sql/"

#指定文件的位置, 没有指定时会自动创建一个临时文件夹
spring:
  servlet:
    multipart:
      location: "D:/springboot/upload/"
  profiles: dev

---

#图片上传路径映射 自定义属性
upload:
  picture:
    path: "/hrsys/springboot/upload/"

#数据库备份路径
sqlbackup:
  path: "/hrsys/springboot/sql/"
  staticPath: "/hrsys/springboot/sql/"

#指定文件的位置, 没有指定时会自动创建一个临时文件夹
spring:
  servlet:
    multipart:
      location: "/hrsys/springboot/upload/"
  profiles:
    active: release